package:
    type:           library
    name:           minii-core
    namespace:      yii
    title:          minii Core
    keywords:       minii

composer.json:
    name:           minii/core

require:
    hiqdev/hidev-hiqdev: "*"
    hiqdev/hidev-php:    "*"
