github:
    name:           hiqdev/minii-core

package:
    type:           library
    name:           core
    namespace:      yii
    headline:       minii Core
    title:          minii - mini Yii
    keywords:       minii, core
    description:    |
        **General goals:**

        - less specific dependencies:
            - fxp/composer-asset-plugin and bower-asset/jquery...
            - yii2-composer
            - require Yii.php
        - more PSR compatibility: PSR-3 and so on
        - easier creation of console only application
        - compatibility with yii2 extensions
        - passing yii2 tests

        **Done:**

        - splitted to parts: core, console, caching, ...
        - no more `composer global require fxp/composer-asset-plugin`
        - no more `yii2-composer`, loading extensions done in other way, see `yii\base\Application::prepareExtensions`
        - no more `require __DIR__ . '/../../vendor/yiisoft/yii2/Yii.php'`
        - no more classes.php
        - working for console apps
        - compatible with phar packaging

        **To do:**

        - remove log from core, use psr-3 logging
        - make it working for web apps
        - much more...

require:
    minii/hidev-vendor: "*"
    hiqdev/hidev-php:   "*"
