github:
    name:           hiqdev/minii-core

package:
    type:           library
    name:           core
    title:          minii - mini Yii
    headline:       minii Core
    keywords:       minii, core
    namespace:      yii
    description:    |
        Minii is not another framework - it's a testing playground.

        **General goals:**

        - full compatibility with yii2 including tests
        - less specific dependencies, remove:
            - fxp/composer-asset-plugin (used hiqdev/composer-asset-plugin instead)
            - require Yii.php
        - more PSR compatibility: PSR-3 and so on
        - easier creation of console only applications

        **Done:**

        - splitted to parts: core, console, caching, i18n, web, mail, ...
        - no more `composer global require fxp/composer-asset-plugin`
        - no more `require __DIR__ . '/../../vendor/yiisoft/yii2/Yii.php'` (done with composer)
        - no more classes.php (done with composer)
        - hiqdev/composer-extension-plugin instead of `yii2-composer`
        - working for console apps
        - compatible with phar packaging

        **Changes made:**

        - use of hiqdev/composer-asset-plugin
        - PHAR compatibility

        **Suggested changes to Yii:**

        - think of breaking up helpers inside of other components:
            - Console to yii2-console
            - Html, Url to yii2-web
            - HtmlPurifier why not put it inside of Html ?
            - ArrayHelper, StringHelper, Inflector to ???
            - Markdown to yii2-markdown
            - VarDumper to yii2-debug
            - ...
        - drop yii\mail\BaseMailer dependency on yii\web\View for it could be used for console only apps
        - think of yii\views
        - PSR-3 logging, remove log from core

        **To do:**

        - split tests
        - much more...

require:
    hiqdev/hidev-php:   "*"
    minii/hidev-vendor: "*"
