github:
    full_name:      hiqdev/minii-core

package:
    type:           library
    name:           core
    title:          minii - mini Yii
    headline:       minii Core
    keywords:       minii, core
    namespace:      yii
    description:    |
        Minii is not another framework - it's a testing playground.

        **General goals:**

        - split framework into components
        - less specific dependencies, remove:
            - fxp/composer-asset-plugin (used hiqdev/composer-asset-plugin instead)
            - require Yii.php
        - more PSR compatibility: PSR-3 and so on
        - easier creation of console only applications

        **Done:**

        - splitted to parts: core, console, caching, i18n, web, mail, ...
        - no more `composer global require fxp/composer-asset-plugin`, used `hiqdev/composer-asset-plugin`
        - no more `require __DIR__ . '/../../vendor/yiisoft/yii2/Yii.php'`, done with composer
        - no more classes.php, done with composer
        - working for console apps
        - compatible with PHAR packaging

        **Changes to PR to yii2:**

        - PHAR compatibility

        **Changes to think of:**

        - move helpers into other components:
            - Console to yii2-console
            - Html, Url to yii2-web
            - ArrayHelper, StringHelper, Inflector to ???
            - Markdown to yii2-markdown
            - VarDumper to yii2-debug
            - ...
        - drop yii\mail\BaseMailer dependency on yii\web\View for it could be used for console only apps
        - PSR-3 logging, remove log from core

        **To do:**

        - try split tests into components
        - much more...

require:
    hiqdev/hidev-php:   "*"
    minii/hidev-vendor: "*"
