package:
    type:           library
    name:           minii-core
    namespace:      yii
    headline:       minii Core
    title:          minii - mini Yii
    keywords:       minii
    description:    |
        **General goals:**
        - less yii specific dependencies
        - more PSR compatibility: PSR-3 and so on
        - easier creation of console only application
        - compatibility with yii2 extensions
        - passing yii2 tests

        **Done:**
        - splitted to parts: core, console, caching, ...
        - no more `composer global require fxp/composer-asset-plugin`
        - no need for `yii2-composer`, loading extensions done in other way, see `yii\base\Application::prepareExtensions`
        - no more `require __DIR__ . '/../../vendor/yiisoft/yii2/Yii.php'`, done with composer autoload files
        - working for console apps

        **To do:**
        - rm log from core, use psr-3 logging
        - make it working for web apps
        - much more...

composer.json:
    name:           minii/core

require:
    hiqdev/hidev-hiqdev: "*"
    hiqdev/hidev-php:    "*"
